pipeline {
    agent {
        docker {
            image 'ubuntu:18.04'
        }
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
          //  agent none
            steps {
                sh "cd $WORKSPACE"
                sh "ls -lrt"
                sh "sudo apt-get install git"
                sh "git clone https://github.com/ravi1312/simple-python-pyinstaller-app.git"
              //  sh 'python -m py_compile sources/add2vals.py sources/calc.py'
                //stash(name: 'compiled-results', includes: 'sources/*.py*')
            }
        }
        stage('Test') {
          //  agent none
            steps {
                echo "test"
              //  sh "zip -r Helloworld.zip $WORKSPACE/sources/add2vals.py"
              //  sh 'py.test --junit-xml test-reports/results.xml sources/test_calc.py'
            }
            //post {
              //  always {
                //    junit 'test-reports/results.xml'
                //}
            //}
        }
        stage('Deliver') { 
           // agent any
            //environment { 
              //  VOLUME = '$(pwd)/sources:/src'
                //IMAGE = 'cdrx/pyinstaller-linux:python2'
            //}
            steps {
                echo "hello"
                sh "cp -r $WORKSPACE/sources/add2vals.py add2vals.py"
                sh "zip -r Helloworld.zip add2vals.py"
                sh "rm -rf add2vals.py"
                //dir(path: env.BUILD_ID) { 
                  //  unstash(name: 'compiled-results') 
                    //sh "docker run --rm -v ${VOLUME} ${IMAGE} 'pyinstaller -F add2vals.py'" 
                //}
            }
            post {
                success {
                    echo "success"
                    //sh "cp -r $WORKSPACE/sources/add2vals.py /var/lib/jenkins/add2vals.py"
                    //sh "zip -r Helloworld.zip /var/lib/jenkins/add2vals.py"
                  //  archiveArtifacts "${env.BUILD_ID}/sources/dist/add2vals" 
                    //sh "docker run --rm -v ${VOLUME} ${IMAGE} 'rm -rf build dist'"
                }
            }
        }
    }
}

