pipeline {
    agent none
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }
            steps {
                sh "cd $WORKSPACE"
                sh "ls -lrt"
              //  sh 'python -m py_compile sources/add2vals.py sources/calc.py'
                //stash(name: 'compiled-results', includes: 'sources/*.py*')
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'qnib/pytest'
                }
            }
            steps {
                echo "test"
              //  sh "zip -r Helloworld.zip $WORKSPACE/sources/add2vals.py"
              //  sh 'py.test --junit-xml test-reports/results.xml sources/test_calc.py'
            }
            //post {
              //  always {
                //    junit 'test-reports/results.xml'
                //}
            //}
        }
        stage('Deliver') { 
            //agent any
            //environment { 
              //  VOLUME = '$(pwd)/sources:/src'
                //IMAGE = 'cdrx/pyinstaller-linux:python2'
            //}
            steps {
                echo "hello"
                //dir(path: env.BUILD_ID) { 
                  //  unstash(name: 'compiled-results') 
                    //sh "docker run --rm -v ${VOLUME} ${IMAGE} 'pyinstaller -F add2vals.py'" 
                //}
            }
            post {
                success {
                    sh "cp -r $WORKSPACE/sources/add2vals.py /var/lib/jenkins/add2vals.py"
                    sh "zip -r Helloworld.zip /var/lib/jenkins/add2vals.py"
                  //  archiveArtifacts "${env.BUILD_ID}/sources/dist/add2vals" 
                    //sh "docker run --rm -v ${VOLUME} ${IMAGE} 'rm -rf build dist'"
                }
            }
        }
    }
}

