pipeline{
  agent any
  parameters {
    string(name: 'BranchName', defaultValue: '', description: 'Mention the Specified Branch Name')
  }
  stages{
    stage("build"){
      steps{
        echo "${params.BranchName}"
        sh """
        sh $WORKSPACE/jenkins/script.sh "${params.BranchName}"
        """
      }
    }
  }
}
